apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-kubernetes-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: foo.localhost
    http:
      paths:
      - backend:
          serviceName: guestbook-helm-guestbook
          servicePort: 8081
